name: verto_chat
description: "VertoChat"

publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  openapi:
    git:
      url: https://github.com/verto-chat/mobile_api_client.git
      ref: main

  #  common
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  talker_bloc_logger: ^5.1.13
  stack_trace: ^1.12.1
  json_annotation: ^4.10.0
  freezed_annotation: ^3.1.0
  package_info_plus: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  cancellation_token: ^2.0.1
  visibility_detector: ^0.4.0+2
  flutter_secure_storage: ^10.0.0
  sqflite_sqlcipher: ^3.4.0
  share_plus: ^12.0.1
  async: ^2.13.0

  #core
  formz: ^0.8.0
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  collection: ^1.19.1
  camera: ^0.11.3
  flutter_udid: ^4.1.1
  swipe_image_gallery: ^0.11.0

  provider: ^6.1.5+1
  context_di: ^0.2.5

  slang: ^4.12.1
  slang_flutter: ^4.12.1

  firebase_core: ^4.4.0
  supabase_flutter: ^2.12.0
  signalr_netcore: ^1.4.4
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7

  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.1

  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0

  uuid: ^4.5.2

  dio: ^5.9.1
  talker_dio_logger: ^5.1.13

  auto_route: ^11.1.0
  rxdart: ^0.28.0
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  file_picker: ^10.3.10
  open_filex: ^4.7.0

  path_provider: ^2.1.5
  path: ^1.9.1
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3

  image_cropper: ^11.0.0

  flutter_chat_core: ^2.9.0
  flutter_chat_ui: ^2.11.1
  flyer_chat_file_message: ^2.4.0
  flyer_chat_image_message: ^2.3.0
  flyer_chat_text_message: ^2.6.0
  gpt_markdown: ^1.1.5

  infinite_scroll_pagination: ^5.1.1
  easy_stepper: ^1.0.1
  flutter_multi_formatter: ^2.13.10
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3

  appmetrica_plugin: ^3.4.0
  appsflyer_sdk: ^6.17.8

  drift: ^2.31.0
  drift_flutter: ^0.2.8

  connectivity_plus: ^7.0.0

  record: ^6.2.0
  just_audio: ^0.10.5

  yx_state: ^1.0.0
  yx_state_flutter: ^1.0.0

  yx_state_provider:
    git:
      url: https://github.com/egorozh/yx_state_provider.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.11.0

  #  common:
  freezed: ^3.2.5
  json_serializable:

  #  main:
  slang_build_runner: ^4.12.1
  slang_gpt: ^0.11.3

  auto_route_generator: ^10.4.0

  flutter_gen_runner: ^5.12.0
  context_di_generator:
    git:
      url: https://github.com/egorozh/context_di.git
      path: context_di_generator
      ref: up-version

  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

  drift_dev: ^2.31.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#232E6E"
  color_dark: "#232E6E"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  android_12:
    color: "#232E6E"
    color_dark: "#232E6E"

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/logo_ios.png"
  remove_alpha_ios: true
