name: ovdix
description: "VertoChat"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #  common
  talker: ^4.9.3
  talker_flutter: ^4.9.3
  talker_bloc_logger: ^4.9.3
  stack_trace: ^1.12.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  package_info_plus: ^8.3.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  cancellation_token: ^2.0.1
  visibility_detector: ^0.4.0+2
  flutter_secure_storage: ^9.2.4
  sqflite_sqlcipher: ^3.2.1
  share_plus: ^11.1.0
  async: ^2.13.0

  #core
  formz: ^0.8.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.2
  intl: ^0.20.2
  collection: ^1.19.1
  camera: ^0.11.2
  flutter_udid: ^4.0.0
  swipe_image_gallery: ^0.10.2

  provider: ^6.1.5
  context_di: ^0.2.4

  slang: ^4.8.1
  slang_flutter: ^4.8.0

  firebase_core: ^4.0.0
  supabase_flutter: ^2.9.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6

  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0

  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

  uuid: ^4.5.1

  dio: ^5.9.0
  retrofit: ^4.7.1
  talker_dio_logger: ^4.9.3

  auto_route: ^10.1.0+1
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  file_picker: ^10.3.1
  open_filex: ^4.7.0

  path_provider: ^2.1.5
  path: ^1.9.1
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0

  image_cropper: ^9.1.0

  flutter_chat_core: ^2.8.0
  flutter_chat_ui: ^2.9.0
  flyer_chat_file_message: ^2.3.1
  flyer_chat_image_message: ^2.2.1
  flyer_chat_text_message: ^2.5.1

  infinite_scroll_pagination: ^5.1.0
  easy_stepper: ^0.8.5+1
  flutter_multi_formatter: ^2.13.8
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.3
  map_launcher: ^4.0.0

  appmetrica_plugin: ^3.2.1
  appsflyer_sdk: ^6.17.1

  objectbox: ^4.3.0
  objectbox_flutter_libs: any

  connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4

  #  common:
  freezed: ^3.1.0
  json_serializable:

  #  main:
  slang_build_runner: ^4.8.0
  slang_gpt: ^0.11.0
  auto_route_generator: any

  flutter_gen_runner: ^5.11.0
  context_di_generator: ^0.2.0

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

  retrofit_generator: ^9.7.0
  objectbox_generator: any

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#EFD2A7"
  color_dark: "#443026"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  android_12:
    color: "#EFD2A7"
    color_dark: "#443026"

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/logo_ios.png"
  remove_alpha_ios: true